from NumPyCreator import NumPyCreator

npc = NumPyCreator()
a = npc.from_list([[1, 2, 3], [6, 3, 4]])
print(a)
a = npc.from_list([[1, 2, 3], [6, 4]])
print(a)
a = npc.from_list([[1, 2, 3], ['a', 'b', 'c'], [6, 4, 7]])
print(a)
a = npc.from_list(((1, 2), (3, 4)))
print(a)
a = npc.from_tuple(("a", "b", "c"))
print(a)
a = npc.from_tuple(["a", "b", "c"])
print(a)
a = npc.from_iterable(range(5))
print(a)
shape = (3, 5)
a = npc.from_shape(shape)
print(a)
a = npc.random(shape)
print(a)
a = npc.identity(4)
print(a)
